version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - fastapi_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fastapi_network

volumes:
  mongo_data:

networks:
  fastapi_network:
